### ISSUE TITLE
Version incompatibility between 2.0 and 2.1

### ISSUE THREAD

**Issue by MiErnst** [AsyncHttpClient/async-http-client#1501]
Hi, I'm confused about the versioning concept of the client. According to this issue #1454 there are API breaks between minor versions and I'm also running into trouble after updating our async-http-client from 2.0.37 to the 2.1.0 version. I don't think changing public API in minor version in a non backward compatible manner is a good idea. Why you don't have released a 3.0 if public API is changed? I don't have trouble with changing public API if necessary but then it should be visible via the major version number.

Exception because of version incompatibilities:
```
Caused by: java.lang.NoSuchMethodError: org.asynchttpclient.DefaultAsyncHttpClientConfig$Builder.setAcceptAnyCertificate(Z)Lorg/asynchttpclient/DefaultAsyncHttpClientConfig$Builder;
	at io.gatling.http.ahc.DefaultAhcFactory.newAhcConfigBuilder(AhcFactory.scala:97)
	at io.gatling.http.ahc.DefaultAhcFactory.<init>(AhcFactory.scala:137)
	at io.gatling.http.ahc.AhcFactory$.apply(AhcFactory.scala:47)```

**Comment by slandelle** [comment]
Hi,

I've just pushed updates in README and CHANGES.

Basically: don't expect SEMVER here.
